- name: Get latest specified version (Debian/Ubuntu)
  when: ansible_facts.os_family == "Debian"
  block:
  - name: Get latest specified version of kubeadm, kubelet and kubectl
    changed_when: true
    register: k8s_version_temp
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        apt-cache madison kubeadm | grep "{{ version }}" | head -n 1 | awk '{print $3}'
      executable: /bin/bash

  - name: Set k8s_version fact
    ansible.builtin.set_fact:
      k8s_version: "{{ k8s_version_temp.stdout }}"

  - name: Update kubeadm k8s_version
    ansible.builtin.apt:
      allow_change_held_packages: true
      name: kubeadm={{ k8s_version }}
      state: present

  - name: Hold kubeadm
    with_items:
    - kubeadm
    ansible.builtin.dpkg_selections:
      name: "{{ item }}"
      selection: hold

- name: Get latest specified version (RedHat/Rocky/Alma/Fedora)
  when: ansible_facts.os_family == "RedHat"
  block:
  - name: Get latest specified version of kubeadm, kubelet and kubectl
    changed_when: true
    register: k8s_version_temp
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        dnf list --showduplicates kubeadm | grep "{{ version }}" | head -n 1 | awk '{print $2}' | cut -d ':' -f 2
      executable: /bin/bash

  - name: Set k8s_version fact
    ansible.builtin.set_fact:
      k8s_version: "{{ k8s_version_temp.stdout }}"

  - name: Remove kubeadm version lock
    changed_when: false
    ansible.builtin.command:
      cmd: dnf versionlock delete kubeadm

  - name: Update kubeadm k8s_version
    ansible.builtin.dnf:
      name: kubeadm-{{ k8s_version }}
      state: present

  - name: Hold kubeadm
    changed_when: false
    ansible.builtin.command:
      cmd: dnf versionlock add kubeadm

- name: Get kubeadm version
  changed_when: false
  register: kubeadm_version
  ansible.builtin.command: kubeadm version -o short
