- name: Update kubelet, kubectl and containerd.io (Debian/Ubuntu)
  when: ansible_facts.os_family == "Debian"
  block:
  - name: Update kubelet and kubectl to specified k8s_version
    with_items:
    - kubelet={{ k8s_version }}
    - kubectl={{ k8s_version }}
    ansible.builtin.apt:
      allow_change_held_packages: true
      name: "{{ item }}"
      state: present

  - name: Resolve containerd package version (Debian/Ubuntu)
    when: kubernetes_containerd_version != "latest"
    changed_when: false
    failed_when: containerd_version_resolved.stdout == ""
    register: containerd_version_resolved
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        apt-cache madison containerd.io | grep "{{ kubernetes_containerd_version }}" | head -n 1 | awk '{print $3}'
      executable: /bin/bash

  # noqa: var-naming[no-role-prefix]
  - name: Set containerd_version fact (Debian/Ubuntu)
    ansible.builtin.set_fact:
      containerd_version: "{{ containerd_version_resolved.stdout if kubernetes_containerd_version != 'latest' else 'latest' }}"

  - name: Upgrade containerd
    ansible.builtin.apt:
      allow_change_held_packages: true
      allow_downgrade: true
      name: "{{ 'containerd.io=' + containerd_version if containerd_version != 'latest' else 'containerd.io' }}"
      only_upgrade: "{{ containerd_version == 'latest' }}"
      state: "{{ 'present' if containerd_version != 'latest' else 'latest' }}"

  - name: Reconfigure containerd for new version
    ansible.builtin.include_role:
      name: containerd
      tasks_from: configure-containerd.yml

  - name: Hold kubelet, kubectl and containerd.io
    with_items:
    - kubelet
    - kubectl
    - containerd.io
    ansible.builtin.dpkg_selections:
      name: "{{ item }}"
      selection: hold

- name: Update kubelet, kubectl and containerd.io (RedHat/Rocky/Alma/Fedora)
  when: ansible_facts.os_family == "RedHat"
  block:
  - name: Remove version locks
    changed_when: true
    with_items:
    - kubelet
    - kubectl
    - containerd.io
    ansible.builtin.command:
      cmd: dnf versionlock delete {{ item }}

  - name: Update kubelet and kubectl to specified k8s_version
    with_items:
    - kubelet-{{ k8s_version }}
    - kubectl-{{ k8s_version }}
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present

  - name: Resolve containerd package version (RedHat)
    when: kubernetes_containerd_version != "latest"
    changed_when: false
    failed_when: containerd_version_resolved.stdout == ""
    register: containerd_version_resolved
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        dnf list --showduplicates containerd.io | grep "{{ kubernetes_containerd_version }}" | tail -n 1 | awk '{print $2}' | cut -d ':' -f 2
      executable: /bin/bash

  # noqa: var-naming[no-role-prefix]
  - name: Set containerd_version fact (RedHat)
    ansible.builtin.set_fact:
      containerd_version: "{{ containerd_version_resolved.stdout if kubernetes_containerd_version != 'latest' else 'latest' }}"

  - name: Upgrade containerd
    ansible.builtin.dnf:
      name: "{{ 'containerd.io-' + containerd_version if containerd_version != 'latest' else 'containerd.io' }}"
      state: "{{ 'present' if containerd_version != 'latest' else 'latest' }}"
      allow_downgrade: true

  - name: Reconfigure containerd for new version
    ansible.builtin.include_role:
      name: containerd
      tasks_from: configure-containerd.yml

  - name: Hold kubelet, kubectl and containerd.io
    changed_when: true
    with_items:
    - kubelet
    - kubectl
    - containerd.io
    ansible.builtin.command:
      cmd: dnf versionlock add {{ item }}

- name: Reload kubelet
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: kubelet
    state: restarted
