- name: Get nodes in the cluster
  changed_when: false
  delegate_to: "{{ first_kube_control_plane }}"
  register: kubernetes_nodes
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o custom-columns=NAME:.metadata.name --no-headers

- name: Check if the node needs to join the cluster
  ansible.builtin.set_fact:
    kubernetes_needs_to_join_cluster: "{% if inventory_hostname in kubernetes_nodes.stdout_lines or inventory_hostname_short in kubernetes_nodes.stdout_lines %}{{ 'false' | bool }}{% else %}{{ 'true' | bool }}{% endif %}"


- name: Join workers to the cluster
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  block:
  - name: Generate Join token
    changed_when: true
    delegate_to: "{{ first_kube_control_plane }}"
    register: temp_token
    ansible.builtin.command:
      cmd: kubeadm token create --ttl 30m

  - name: Set facts
    ansible.builtin.set_fact:
      cluster_ca_cert_hash: "{{ hostvars[first_kube_control_plane].cluster_ca_cert_hash }}"
      join_token: "{{ temp_token.stdout }}"

  - name: Create kubeadm file
    register: kubeadm_file
    when:
    - kubernetes_needs_to_join_cluster
    ansible.builtin.template:
      backup: true
      dest: "{{ kubernetes_config_directory }}/kubeadm.yaml"
      group: root
      mode: '0644'
      owner: root
      src: worker-kubeadm-{{ kubernetes_version }}.yaml.j2

  - name: Post configure worker hooks
    when:
    - kubernetes_hookfiles.post_configure_workers is defined
    with_items: "{{ kubernetes_hookfiles.post_configure_workers }}"
    ansible.builtin.include_tasks: "{{ item }}"

  - name: Stop kubelet service
    when:
    - kubernetes_needs_to_join_cluster
    ansible.builtin.systemd:
      enabled: true
      name: kubelet
      state: stopped

  - name: Add the worker node
    changed_when: kubernetes_join_output.rc == 0
    register: kubernetes_join_output
    when:
    - kubernetes_needs_to_join_cluster
    ansible.builtin.command:
      cmd: kubeadm join --config {{ kubernetes_config_directory }}/kubeadm.yaml {{ kubernetes_kubeadm_join_extra_args | default('') }}

  - name: Expire join token
    changed_when: true
    delegate_to: "{{ first_kube_control_plane }}"
    when: join_token is defined
    ansible.builtin.command:
      cmd: kubeadm token delete "{{ join_token }}"

  rescue:
  - name: Expire join token
    changed_when: true
    delegate_to: "{{ first_kube_control_plane }}"
    when: join_token is defined
    ansible.builtin.command:
      cmd: kubeadm token delete "{{ join_token }}"

  - name: Fail worker node join
    ansible.builtin.fail:
      msg: >-
        Joining worker node {{ inventory_hostname }} to the cluster failed.

# CIS 1.1.20
- name: CIS 1.1.20 - Secure certificates
  ansible.builtin.file:
    mode: '0600'
    path: "{{ kubernetes_pki_directory }}"
    recurse: true

# CIS 4.1.1
- name: CIS 4.1.1 - Set kubelet.service file permissions to 0600
  ansible.builtin.file:
    mode: '0600'
    path: /usr/lib/systemd/system/kubelet.service

# CIS 4.1.2
# CIS 4.1.9
# STIG V-242407
- name: CIS 4.1.9, STIG V-242407 - Set kubelet config.yaml file permissions to 0600
  ansible.builtin.file:
    mode: '0600'
    path: /var/lib/kubelet/config.yaml

# STIG V-242397
- name: Secure static pod path
  ansible.builtin.replace:
    path: /var/lib/kubelet/config.yaml
    regexp: 'staticPodPath:.*'
    replace: 'staticPodPath:'

- name: Restart kubelet
  when:
  - kubernetes_needs_to_join_cluster
  ansible.builtin.service:
    enabled: true
    name: kubelet
    state: restarted

- name: Post security hooks
  loop: "{{ kubernetes_hookfiles.post_security }}"
  loop_control:
    loop_var: post_security_hook
  when:
  - kubernetes_hookfiles.post_security is defined
  ansible.builtin.include_tasks:
    file: "{{ post_security_hook }}"

- name: Post worker node join hooks
  loop: "{{ kubernetes_hookfiles.post_worker_join }}"
  loop_control:
    loop_var: post_worker_node_join_hook
  when:
  - kubernetes_hookfiles.post_worker_join is defined
  ansible.builtin.include_tasks:
    file: "{{ post_worker_node_join_hook }}"

# Get an updated list of nodes in the cluster
- name: Wait for node to appear in cluster
  changed_when: false
  delay: 2
  delegate_to: "{{ first_kube_control_plane }}"
  register: kubernetes_nodes
  retries: 15
  until: inventory_hostname in kubernetes_nodes.stdout_lines or inventory_hostname_short in kubernetes_nodes.stdout_lines
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o custom-columns=NAME:.metadata.name --no-headers

- name: Set the node name fact
  ansible.builtin.set_fact:
    kubernetes_node_name: "{% if inventory_hostname in kubernetes_nodes.stdout_lines %}{{ inventory_hostname }}{% elif inventory_hostname_short in kubernetes_nodes.stdout_lines %}{{ inventory_hostname_short }}{% endif %}"

# This kubectl command returns all certificate signing requests for the node, one per line
- name: Get certificate signing requests
  changed_when: false
  delegate_to: "{{ first_kube_control_plane }}"
  register: csr_check
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /etc/kubernetes/admin.conf get csr -o jsonpath='{range .items[?(@.spec.username=="system:node:{{ kubernetes_node_name }}")]}{.metadata.name}{"\n"}{end}'

- name: Approve certificate signing requests
  changed_when: true
  delegate_to: "{{ first_kube_control_plane }}"
  loop: "{{ csr_check.stdout_lines }}"
  loop_control:
    loop_var: csr_name
  when:
  - csr_check.stdout_lines | length > 0
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /etc/kubernetes/admin.conf certificate approve "{{ csr_name }}"
