services:
  devcontainer:
    devices:
    - /dev/kvm:/dev/kvm
    environment:
    - DEVCONTAINER=true
    extra_hosts:
    - "cp.k8s.local:127.0.0.1"
    - "px.k8s.local:127.0.0.1"
    - "cp1.k8s.local:127.0.0.1"
    - "cp2.k8s.local:127.0.0.1"
    - "cp3.k8s.local:127.0.0.1"
    - "w1.k8s.local:127.0.0.1"
    - "w2.k8s.local:127.0.0.1"
    image: quay.io/cyclops-k8s/ansible-kubernetes-devcontainer:latest
    volumes:
    - ..:/workspace:cached
    - ~/.ssh:/host/.ssh:ro
    network_mode: bridge
