# Required
# This is the IP address of the Kubernetes control plane. This is the IP address that the proxies will bind to.
kubernetes_control_plane_ip: null

# This is deprecated starting in containerd 2.0.0
# kubernetes_containerd_credentials:
# - username: "username"
#   password: "password"
#   registry: "https://index.docker.io/v1/"
kubernetes_containerd_credentials: []

# Apt/Yum repository to pull containerd from
kubernetes_containerd_mirror_deb: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}"
kubernetes_containerd_mirror_rpm: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
kubernetes_containerd_mirror: "{% if ansible_facts.os_family == 'Debian' %}{{ kubernetes_containerd_mirror_deb }}{% else %}{{ kubernetes_containerd_mirror_rpm }}{% endif %}"
kubernetes_containerd_mirror_gpgkey_deb: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg"
kubernetes_containerd_mirror_gpgkey_rpm: "https://download.docker.com/linux/centos/gpg"
kubernetes_containerd_mirror_gpgkey: "{% if ansible_facts.os_family == 'Debian' %}{{ kubernetes_containerd_mirror_gpgkey_deb }}{% else %}{{ kubernetes_containerd_mirror_gpgkey_rpm }}{% endif %}"

# This version of kubernetes_containerd_registry_mirrors is deprecated as of containerd version 2.0.0
# This configuration works for versions below 2.2.0
# Instructs containerd to use registry mirrors. Multiple enpoints can be defined in a list.
# Reference:
# https://github.com/containerd/containerd/blob/main/docs/cri/registry.md
# kubernetes_containerd_registry_mirrors:
# - registry: docker.io
#   endpoints:
#   - https://dockermirror.example.com:5001
# - registry: quay.io
#   endpoints:
#   - https://quaymirror.example.com:5002
# - registry: registry.k8s.io
#   endpoints:
#   - https://k8smirror.example.com:5003
#
# Used for containerd versions greater than or equal to 2.2.0
# Refer to containerd's documentation for host and server options:
# https://github.com/containerd/containerd/blob/main/docs/hosts.md
# kubernetes_containerd_registry_mirrors:
# - registry: docker.io
#   extra_files:
#   - name: ca.pem
#     content: |
#       file content
#   - name: client.cert
#     content: |
#       file content
#   - name: client.key
#     content: |
#       file content
#   hosts:
#   - host: "https://dockermirror.example.com:5001"
#     ca: "ca.pem"
#     capabilities: '["pull", "resolve"]'
#     client: '[["client.cert", "client.key"]]'
#     dial_timeout: "5s"
#     override_path: false
#     skip_verify: false
#     headers:
#     - name: Authorization
#       value: "Basic <base64 encoded username:password>"
#   server:
kubernetes_containerd_registry_mirrors: []

# CIS 1.1.12 - Ensure that the etcd data directory ownership is set to etcd:etcd
kubernetes_etcd_init_container_image: alpine:latest

# CIS 1.1.12 - Ensure that the etcd data directory ownership is set to etcd:etcd
kubernetes_etcd_group_id: 500

# CIS 1.1.12 - Ensure that the etcd data directory ownership is set to etcd:etcd
kubernetes_etcd_user_id: 500

kubernetes_admission_control_plugins:
# CIS 1.2.11 - Ensure that the admission control plugin AlwaysPullImages is set)
- AlwaysPullImages

# CIS 1.2.14 - Ensure that the admission control plugin NodeRestriction is set (included by default)
- NodeRestriction

# Defaults as of 1.35
- CertificateApproval
- CertificateSigning
- CertificateSubjectRestriction
- DefaultIngressClass
- DefaultStorageClass
- DefaultTolerationSeconds
- LimitRanger
- MutatingAdmissionWebhook
- NamespaceLifecycle
- PersistentVolumeClaimResize
- PodSecurity
- Priority
- ResourceQuota
- RuntimeClass
- ServiceAccount
- StorageObjectInUseProtection
- TaintNodesByCondition
- ValidatingAdmissionPolicy
- ValidatingAdmissionWebhook

# STIG V-254800
kubernetes_admission_configuration:
  audit: "baseline"
  audit_version: "latest"
  enforce: "privileged"
  enforce_version: "latest"
  exemptions:
    usernames:
    - admin
    namespaces:
    - kube-system
  warn: "privileged"
  warn_version: "latest"

# Required
# This is the FQDN of the control plane API endpoint.
# Your clients will use this endpoint to interface with the cluster.
# This DNS entry should already be setup before running the playbooks.
kubernetes_api_endpoint: null

# Port for the load balanced API.
kubernetes_api_port: 6443

# Expects an array of dictionaries with the following keys: name, source, destination (optional), mode
# mode defaults to File
# destination defaults to the same value as source
# name must be unique and not any of the following
# - authentication
# - authorization
# - encryption-config
# - audit-policy
# - audit-log
# - admission-configuration
# - ca-certs
# - etc-ca-certificates
# - k8s-certs
# - usr-local-share-ca-certificates
# - usr-share-ca-certificates

# Example:
# kubernetes_api_server_additional_mounts:
# - name: example-mount
#   source: /etc/kubernetes/config
#   destination: /opt/config
#   mode: "0600"
kubernetes_api_server_additional_mounts: []

# Extra arguments to pass to the Kubernetes API Server
# Must not contain any of the following names:
# audit-log-path
# audit-log-maxage
# audit-log-maxbackup
# audit-log-maxsize
# tls-cipher-suites
# audit-policy-file
# authentication-config
# authorization-config
# enable-admission-plugins
# encryption-provider-config
# encryption-provider-config-automatic-reload
# kubelet-certificate-authority
# profiling
# admission-control-config-file
# tls-min-version
# service-account-issuer

# Example:
# kubernetes_api_server_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_api_server_extra_args: []

# IP address for the API server to bind to, null to lookup the IP address using the FQDN
# If you set this to 0.0.0.0 then it will bind to all interfaces
kubernetes_api_server_bind_address: null

# Port for the API server to bind to, usually 6443
kubernetes_api_server_port: 6443

# CIS 1.2.17 - Ensure that the --audit-log-maxage argument is set to 30 or as appropriate
# STIG V-242464
kubernetes_audit_log_max_age: 30

# CIS 1.2.18 - Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Automated)
# STIG V-242463
kubernetes_audit_log_max_backup: 10

# CIS 1.2.19 - Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate
# STIG V-242462
kubernetes_audit_log_max_size: 100

# CIS 1.2.16 - Ensure that the --audit-log-path argument is set
# STIG V-242465
# STIG V-242402
kubernetes_audit_log_path: /var/log/apiserver/audit.log

# The next 3 are part of:
# CIS 1.2.6 - Ensure that the --authorization-mode argument is not set to AlwaysAllow
# CIS 1.2.7 - Ensure that the --authorization-mode argument includes Node
# CIS 1.2.8 - Ensure that the --authorization-mode argument includes RBAC
# STIG V-242382
kubernetes_authorization_pre_node: []
kubernetes_authorization_pre_rbac: []
kubernetes_authorization_post_rbac: []

# If set, it must be external
kubernetes_cloud_provider: null

# Directory to store configuration for the playbook and Kubernetes components in
kubernetes_config_directory: /etc/kubernetes/config

# Additional files to copy to control plane nodes. This only copies files, it does not use them as a template
# Expects an array of object containing source, destination and mode (defaults to 0600)

# Example:
# kubernetes_control_plane_additional_files:
# - source: "{{ inventory_dir }}/somefile.yaml.j2"
#   destination: "/etc/kubernetes/config/somefile.yaml"
#   mode: "0644"
kubernetes_control_plane_additional_files: []

# Additional files to copy to control plane nodes. This will run these files through the template, passing in variables.
# Expects an array of object containing source, destination and mode (defaults to 0600)

# Example:
# kubernetes_control_plane_additional_templates:
# - source: "{{ inventory_dir }}/somefile.yaml.j2"
#   destination: "/etc/kubernetes/config/somefile.yaml"
#   mode: "0644"
kubernetes_control_plane_additional_templates: []

# How frequently the proxies will check if the control plane is functioning
kubernetes_control_plane_check_interval: 100ms

# Timeout for the control plane to respond during health checks
kubernetes_control_plane_timeout: 4m0s

# Extra arguments to pass to the Kubernetes Controller Manager
# Must not contain any of the following names:
# authentication-tolerate-lookup-failure
# node-cidr-mask-size
# terminated-pod-gc-threshold
# cluster-signing-duration
# profiling
# tls-min-version

# Example:
# kubernetes_controller_manager_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_controller_manager_extra_args: []

# How long the cluster certificate will remain valid
kubernetes_cluster_signing_duration: 8760h

# The name of the cluster, usually can be whatever you want
kubernetes_cluster_name: cluster

# Configure SELinux on RPM-based systems (RHEL, Rocky, AlmaLinux, Fedora)
# When true, SELinux will be configured on the proxy servers for HAProxy to be able to listen on all ports.
# Set to false if you manage SELinux policy externally
kubernetes_configure_selinux: true

# The domain name for the cluster, this is used in-cluster to resolve things like services and pods
kubernetes_dns_domain: cluster.local

# Additionally allowed encryption keys for decrypting the etcd data, this should be a list of base64 encoded 32 byte keys.
# This is used for key rotation, you can add new keys here and then remove old keys after the rotation is complete.
# Example value
# kubernetes_encryption_additional_keys:
# - name: key1
#   key: Z8s...Qw=
# - name: key2
#   key: 3d9...CU=
# When rotating keys you will want to add the old `kubernetes_encryption_key_name` and `kubernetes_encryption_key`
# to this list with a unique id, then update `kubernetes_encryption_key_name` and `kubernetes_encryption_key` to
# the new key. After the rotation is complete and you are sure the old key is no longer needed, you can remove it
# from this list. You must not change the key id from what was originally in `kubernetes_encryption_key_name` when
# adding it to the list, as the key id is what identifies the key to use in the etcd data.
kubernetes_encryption_additional_keys: []

# The configuration template to use for encrypting the etcd data, this should be a file that is compatible with the
# kube-apiserver --encryption-provider-config flag. This defaults to using the template file that is included in the
# role named `encryption-{{ kubernetes_version }}.yaml.j2`
kubernetes_encryption_configuration_file: null

# Required
# 32 bytes used to encrypt the etcd data, this should be base64 encoded.
# You can generate one with `head -c 32 /dev/urandom | base64`
# This is the encryption key that will be used to encrypt the data in etcd. This should be a base64 encoded 32 byte key.
kubernetes_encryption_key: null
kubernetes_encryption_key_name: key1

# Extra arguments to pass to the ETCD backend
# Must not contain any of the following names:
# authentication-tolerate-lookup-failure
# peer-auto-tls
# auto-tls

# Example:
# kubernetes_etcd_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_etcd_extra_args: []

# in order of execution
kubernetes_hookfiles:
  # run before any tasks that configure the proxies
  pre_proxies: []

  # run after the tasks that configure the proxies
  post_proxies: []

  # At the beginning of every major section run these, this is a good spot to put in default variables and validations
  default_configuration: []

  # At the beginning of installing pre-requisites.
  pre_prerequisites: []

  # After installing packages
  post_install_packages: []

  # Before installing control planes
  pre_configure_control_planes: []

  # After configuring the control planes with the required configuration files
  post_configure_control_planes: []

  # After configuring the workers with the required configuration files
  post_configure_workers: []

  # Before the control plane has been initialized or control planes have been joined
  pre_control_planes: []

  # After the cluster has been initialized and before anything has been added or configured in the cluster.
  # Host level security policies that are deferred to after the cluster creation are not applied yet.
  # This is where you want to install your CNI, see the `example-hooks/post_cluster_init` directory for examples.
  post_cluster_init: []

  # Executes after the node has been joined to the cluster and after security policies have applied.
  post_security: []

  # after the additional control plane has been joined to the cluster
  post_control_plane_join: []

  # after all control planes have been joined to the cluster
  post_control_planes: []

  # after the worker node has been joined to the cluster
  post_worker_join: []

  # after all worker nodes have been joined to the cluster
  post_workers: []

  # During a cluster upgrade, before any control planes are upgraded
  pre_upgrade_control_planes: []

  # During a cluster upgrade, after the control plane kubeadm upgrade is completed
  post_upgrade_control_planes: []

  # During a cluster upgrade, before any workers are upgraded
  pre_upgrade_workers: []

  # During a cluster upgrade, after the worker kubeadm upgrade is completed
  post_upgrade_workers: []

  # During a cluster upgrade, after kubelet, kubectl and containerd have been upgraded and reconfigured
  post_upgrade: []

# Phases to skip in the kubeadm init process, you can view the list of phases by checking out `kubeadm init --help`
kubernetes_init_skip_phases: []

# Extra arguments to add to kubeadm init. This is added verbatim to the end of the `kubeadm init` command
kubernetes_kubeadm_init_extra_args: ""

# Extra arguments to add to kubeadm join. This is added verbatim to the end of the `kubeadm join` command
kubernetes_kubeadm_join_extra_args: ""

# Manage automatic renewal of Kubernetes node (KubeScheduler/APIServer/Etcd/etc) certificates by a systemd timer unit
kubernetes_manage_cert_renewal: true

# Apt/Yum mirror to pull the Kubernetes packages from
kubernetes_deb_mirror: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb"
kubernetes_rpm_mirror: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/rpm"
kubernetes_mirror: "{% if ansible_facts.os_family == 'Debian' %}{{ kubernetes_deb_mirror }}{% else %}{{ kubernetes_rpm_mirror }}{% endif %}"

# The internal Kubernetes node cidr for pods
kubernetes_node_cidr_mask_size: 24

# Where to store output files for this playbook
kubernetes_output_directory: /etc/kubernetes/output

# Where to put the certificates for Kubernetes that are generated by kubeadm.
kubernetes_pki_directory: /etc/kubernetes/pki

# The internal CIDR for all of the pod's. Must be large enough to accomodate the CIDR subnet size above for all nodes.
kubernetes_pod_subnet: 10.244.0.0/16

# CIS 4.2.13 - Ensure that a limit is set on pod PIDs
kubernetes_podpidslimit: 1000

# CIS 1.2.15, 1.3.2, 1.4.1 - Profiling should be turned off. Default in kubeadm is true.
# STIG V-242409
kubernetes_profiling: false

# Port for the proxy to listen on, usually 6443
kubernetes_proxy_port: 6443

# IP address for the proxy to bind to, blank or 0.0.0.0 to bind to all interfaces
kubernetes_proxy_bind_address: ""

# Template file to use for configuring HAProxy on the proxy nodes
kubernetes_proxy_haproxy_config_file: haproxy.cfg.j2

# Template file to use for configuring Keepalived on the proxy nodes
kubernetes_proxy_keepalived_config_file: keepalived.conf.j2

# Extra arguments to pass to the Kubernetes Scheduler
# Must not contain any of the following names:
# authentication-tolerate-lookup-failure
# profiling
# tls-min-version

# Example:
# kubernetes_scheduler_extra_args:
# - name: somearg
#   value: somevalue
kubernetes_scheduler_extra_args: []

# Directory to store scripts for Kubernetes on the nodes
kubernetes_scripts_directory: /opt/kubernetes/scripts

# CIS 4.2.14 - Ensure that seccomp is enabled by default in the Kubelet
kubernetes_seccomp_default: true

# CIS 1.2.30 - Ensure that the --service-account-extend-token-expiration argument is set to false
kubernetes_service_account_extend_token_expiration: false

# Subnet for the cluster services running in the Kubernetes cluster
kubernetes_service_subnet: 10.96.0.0/16

# Supported Kubernetes minor versions, do not customize this unless you know what you are doing
kubernetes_supported_versions:
- "1.33"
- "1.34"
- "1.35"

# CIS 4.2.5 - Ensure that the --streaming-connection-idle-timeout argument is not set to 0
# STIG V-245541 - States this should be 5 minutes
kubernetes_streamingconnectionidletimeout: 5m

# CIS 1.3.1 Ensure that the --terminated-pod-gc-threshold argument is set as appropriate
kubernetes_terminated_pod_gc_threshold: 10

# Required
# This is the issuer URL of the OIDC provider. Do not include the .well-known/openid-configuration path.
kubernetes_oidc_issuer_url: null

# Required
# This is the client ID of the OIDC provider.
kubernetes_oidc_client_id: null

# Claim inside the OIDC token that states the username
kubernetes_oidc_username_claim: upn

# Use expression instead of claim for the OIDC username
kubernetes_oidc_username_expression: null

# Prefix to add to the username for logs and authorization
kubernetes_oidc_username_prefix: "oidc:"

# Claim inside the OIDC token that has the list of roles assigned to the user
kubernetes_oidc_group_claim: roles

# Prefix to add to the roles for logs and authorization
kubernetes_oidc_group_prefix: "oidc:"

# Claim inside the OIDC token that has the unique object id, useful for logging
kubernetes_oidc_uid_claim: oid

# You can override the default, which is https://kubernetes.default.svc.cluster.local, with any url.
kubernetes_service_account_issuer: null

# CIS 4.2.12 - Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers
# STIG V-242418
kubernetes_strong_cypher_suites:
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

# The minor version of Kubernetes to install. Do not include the patch version, like 1.31.2. Just do the minor, like 1.31.
kubernetes_version: "1.35"

# Done run the kubernetes-default validation checks. It is not recommended to skip these unless you know what you are doing.
skip_checks: false

# Required
# This is the password used by keepalived in the proxy nodes to move the floating ip between proxy nodes
vrrp_password: null

# Required
# The floating Kubernetes control plane IP address will live on this interface
vrrp_interface: null

# Required
# The virtual router id for the Kubernetes control plane keepalived instance
vrrp_virtual_router_id: null

# Required
# The initial state of the keepalived instance on this node, either MASTER or BACKUP
# This shouldn't reeally be needed. BACKUP should be fine. We should get rid of this.
vrrp_state: BACKUP

# Registry mirrors to add to containerd configuration
# containerd_registry_mirrors:
# - registry: docker.io
#   endpoints:
#     - https://my.localserver.me:5001
# - registry: quay.io
#   endpoints:
#     - https://my.localserver.me:5002
# - registry: registry.k8s.io
#   endpoints:
#     - https://my.localserver.me:5004
# - registry: docker.elastic.co
#   endpoints:
#     - https://my.localserver.me:5003
