# Fixes issue #52: Rebalance the CoreDNS deployment
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#:~:text=the%20given%20key.-,Note%3A,restart%20deployment%20coredns%20after%20at%20least%20one%20new%20node%20is%20joined.,-External%20etcd%20nodes

- name: Rebalance the CoreDNS deployment
  changed_when: false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.command:
    cmd: kubectl -n kube-system rollout restart deployment coredns

- name: Wait for CoreDNS to rebalance
  changed_when: false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ansible.builtin.command:
    cmd: kubectl -n kube-system rollout status deployment coredns --timeout=120s
