- name: Install Cilium
  delegate_to: "{{ first_kube_control_plane }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  run_once: true
  block:
  - name: Check for Calico
    register: calico_installed_cmd
    ansible.builtin.shell:
      cmd: |
        kubectl get pods --namespace kube-system 2> /dev/null | grep calico > /dev/null 2> /dev/null || echo "Not installed"
        echo "Installed"

  - name: Set install_calico fact
    ansible.builtin.set_fact:
      install_calico: "{{ calico_installed_cmd.stdout_lines[0] == 'Not installed' }}"

  - name: Install Calico
    register: calico
    when: install_calico
    ansible.builtin.command:
      cmd: "kubectl apply -f {{ calico_manifest_url | default('https://raw.githubusercontent.com/projectcalico/calico/v3.31.3/manifests/calico.yaml', true) }}"

  - name: Wait for Calico to be ready
    delay: 1
    register: calico_pods
    retries: 300
    until: calico_pods.rc == 0
    when: install_calico
    ansible.builtin.command:
      cmd: kubectl wait --for=condition=Ready pod -l k8s-app=calico-node --timeout=1s --namespace kube-system

  rescue:
  - name: Calico variable contents
    ansible.builtin.debug:
      msg:
        calico_installed_cmd: '{{ calico_installed_cmd | default("Not ran") }}'
        install_calico: '{{ install_calico | default("Not ran") }}'
        calico: '{{ calico | default("Not ran") }}'
        calico_pods: '{{ calico_pods | default("Not ran") }}'

  - name: Calico failed
    ansible.builtin.fail:
      msg: Calico failed to install
