- name: Install containerd (Debian/Ubuntu)
  when: ansible_facts.os_family == "Debian"
  block:
  - name: Update apt repositories
    ansible.builtin.apt:
      update_cache: true

  - name: Make sure the gpg package is installed
    ansible.builtin.apt:
      name:
      - gpg
      state: present

  - name: Create keyring directory
    ansible.builtin.file:
      group: root
      mode: '0755'
      owner: root
      path: /etc/apt/keyrings
      state: directory

  - name: Download GPG keyring
    ansible.builtin.get_url:
      dest: /etc/apt/keyrings/docker
      group: root
      mode: '0644'
      owner: root
      url: "{{ kubernetes_containerd_mirror_gpgkey }}"

  - name: Dearmor gpg keyring
    ansible.builtin.command:
      cmd: gpg --batch --yes --dearmor /etc/apt/keyrings/docker
      creates: /etc/apt/keyrings/docker.gpg

  - name: Set GPG keyring permissions
    ansible.builtin.file:
      group: root
      mode: '0644'
      owner: root
      path: /etc/apt/keyrings/docker.gpg
      state: file

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      filename: docker
      repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] {{ kubernetes_containerd_mirror }} {{ ansible_facts["distribution_release"] | lower }} stable
      state: present
      update_cache: true

  - name: Resolve containerd package version (Debian/Ubuntu)
    when: kubernetes_containerd_version != "latest"
    changed_when: false
    failed_when: containerd_version_resolved.stdout == ""
    register: containerd_version_resolved
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        apt-cache madison containerd.io | grep "{{ kubernetes_containerd_version }}" | head -n 1 | awk '{print $3}'
      executable: /bin/bash

  # noqa: var-naming[no-role-prefix]
  - name: Set containerd_version fact (Debian/Ubuntu)
    ansible.builtin.set_fact:
      containerd_version: "{{ containerd_version_resolved.stdout if kubernetes_containerd_version != 'latest' else 'latest' }}"

  - name: Install containerd
    ansible.builtin.apt:
      name:
      - "{{ 'containerd.io=' + containerd_version if containerd_version != 'latest' else 'containerd.io' }}"
      state: "{{ 'present' if containerd_version != 'latest' else 'latest' }}"
      allow_downgrade: true

  - name: Hold containerd.io
    ansible.builtin.dpkg_selections:
      name: containerd.io
      selection: hold

- name: Install containerd (RedHat/Rocky/Alma/Fedora)
  when: ansible_facts.os_family == "RedHat"
  block:
  - name: Add Docker CE repository
    ansible.builtin.yum_repository:
      baseurl: "{{ kubernetes_containerd_mirror }}"
      description: Docker CE Stable - $basearch
      enabled: true
      gpgcheck: true
      gpgkey: "{{ kubernetes_containerd_mirror_gpgkey }}"
      name: docker-ce-stable

  - name: Install versionlock plugin
    ansible.builtin.dnf:
      name: python3-dnf-plugin-versionlock
      state: present

  - name: Resolve containerd package version (RedHat)
    when: kubernetes_containerd_version != "latest"
    changed_when: false
    failed_when: containerd_version_resolved.stdout == ""
    register: containerd_version_resolved
    ansible.builtin.shell:
      cmd: |
        set -eo pipefail
        dnf list --showduplicates containerd.io | grep "{{ kubernetes_containerd_version }}" | tail -n 1 | awk '{print $2}' | cut -d ':' -f 2
      executable: /bin/bash

  # noqa: var-naming[no-role-prefix]
  - name: Set containerd_version fact (RedHat)
    ansible.builtin.set_fact:
      containerd_version: "{{ containerd_version_resolved.stdout if kubernetes_containerd_version != 'latest' else 'latest' }}"

  - name: Install containerd
    ansible.builtin.dnf:
      name:
      - "{{ 'containerd.io-' + containerd_version if containerd_version != 'latest' else 'containerd.io' }}"
      state: "{{ 'present' if containerd_version != 'latest' else 'latest' }}"
      allow_downgrade: true

  - name: Hold containerd.io
    changed_when: true
    ansible.builtin.command:
      cmd: dnf versionlock add containerd.io

- name: Configure containerd
  ansible.builtin.include_tasks:
    file: configure-containerd.yml
